### ISSUE TITLE
jupyter notebook

### ISSUE THREAD

**Issue by LNUitTutor** [BogdanYatsiv/pmo-project#4]
Внести правки, перелічені в коментарі до commit'у

**Comment by BogdanYatsiv** [comment]
Повідомив виконавців

**Comment by BogdanYatsiv** [comment]
більшу частину правок внесли але не зрозуміло що не так з ядом G, він записаний так само як ви показували.

**Comment by LNUitTutor** [comment]
GitHub загалом добре відображає ноутбуки, але ядра він не спромігся намалювати. От я й подумав, що щось не так. Якщо завантажити файл собі на комп і відкрити його в юпітері, то все гаразд.

**Comment by LNUitTutor** [comment]
Ок
