### ISSUE TITLE
unit tests

### ISSUE THREAD

**Issue by LNUitTutor** [BogdanYatsiv/pmo-project#7]
У проекті нема жодного тесту. Ні одна частина залитого функціоналу не перевірена. Треба терміново виправити ситуацію!

**Comment by BogdanYatsiv** [comment]
тести в процесі

**Comment by BogdanYatsiv** [comment]
богдан почне над ними працювати ввечері, коли приїде в гуртожиток, Ростик нічого не казав ще:)

**Comment by BogdanYatsiv** [comment]
Тести  добавлені [https://github.com/BogdanYatsiv/pmo-project/commit/2ad01cbda41acc71267ba5886b874c22e1f9f2c0](url)
